# ═══════════════════════════════════════════════════════════════
# AeroSpace Configuration
# ═══════════════════════════════════════════════════════════════

# Main modkey
after-login-command = []
after-startup-command = []

# Gaps
gaps.inner.horizontal = 8
gaps.inner.vertical = 8
gaps.outer.left = 8
gaps.outer.bottom = 8
gaps.outer.top = 8
gaps.outer.right = 8

# Layouts
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

# Mouse follows focus
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

# Mode configuration
[mode.main.binding]
# Focus windows
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# Move windows
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Resize windows
alt-ctrl-h = 'resize width -50'
alt-ctrl-j = 'resize height +50'
alt-ctrl-k = 'resize height -50'
alt-ctrl-l = 'resize width +50'

# Workspace navigation
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'

# Move to workspace
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'

# Layout commands
alt-s = 'layout tiles horizontal vertical'
alt-t = 'layout tiles'
alt-f = 'layout floating tiling'
alt-shift-f = 'fullscreen'

# Split
alt-v = 'split vertical'
alt-b = 'split horizontal'

# Float/tile toggle
alt-shift-space = 'layout floating tiling'

# Balance
alt-shift-b = 'balance-sizes'

# Reload config
alt-shift-r = 'reload-config'

# Resize mode
alt-r = 'mode resize'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
shift-h = 'resize width -10'
shift-j = 'resize height +10'
shift-k = 'resize height -10'
shift-l = 'resize width +10'
escape = 'mode main'
enter = 'mode main'

# Workspace rules
[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'com.apple.Safari'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = 'move-node-to-workspace 4'
